//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\CodeQulityAnalyzerTestDlls\Microsoft.CodeQuality.CSharp.Analyzers.dll.
        /// </summary>
        internal static string CodeQualityCSharpDllPath {
            get {
                return ResourceManager.GetString("CodeQualityCSharpDllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\CodeQulityAnalyzerTestDlls\Microsoft.CodeQuality.Analyzers.dll.
        /// </summary>
        internal static string CodeQualityDllPath {
            get {
                return ResourceManager.GetString("CodeQualityDllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..CodeStyle\Microsoft.CodeAnalysis.CodeStyle.dll.
        /// </summary>
        internal static string CodeStyle {
            get {
                return ResourceManager.GetString("CodeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\RulesExtracorCLI\bin\Debug\net6.0\RulesExtracorCLI.exe.
        /// </summary>
        internal static string ExtractorExePath {
            get {
                return ResourceManager.GetString("ExtractorExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\MaroontressOxbind\Maroontress.Oxbind.dll.
        /// </summary>
        internal static string MaroontressOxbind {
            get {
                return ResourceManager.GetString("MaroontressOxbind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Temp\ReleaseAttempts\RulesExtracorCLI.exe.
        /// </summary>
        internal static string ReleasePath {
            get {
                return ResourceManager.GetString("ReleasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\UnityAnalyzerTestDlls\Microsoft.Unity.Analyzers.dll.
        /// </summary>
        internal static string UnityAnalyzersPath {
            get {
                return ResourceManager.GetString("UnityAnalyzersPath", resourceCulture);
            }
        }
    }
}
